var bingoItems = [
    // Add bingo items to this list. If you must use the double quote character (") in an item, escape it like this: \"
"No Essence",
"Double Banner User",
"Stoneskin 2 Spotted",
"Forgets Aethershield",
"Dropped in Non-Pure",
"Doom Dice",
"Poison Trapped popped (non-meme)",
"Mini-Trap Popped (non-meme)",
"Explosive Trap popped (not meme)",
"Rainbow Road",
"Big Red Slime",
"Duel Fails",
"Hello Chat :3 moment",
"Queen's Guard Tether Moment",
"AFK kicked",
"Host forgets an action",
"Murder/Soft Chess Miscall",
"Super Chess Miscall",
"Duelist tankbusters",
"Excellence on the Left",
"Dahu Early Pulled (No duelist buff)",
"Early Pull (in general)",
"Instance Crashed",
"Golems Wipe",
"Pure gets culled",
"Non-duelist takes pad",
"All lightning orbs popped",
"16+ clears",
"Damage down in QG",
"No Banish",
"Phantom Death Wall",
"Shell/Protect 1 used (non-meme)",
"Empty Bag Drop",
"Someone has a crashes out",
"Someone hot-mics",
"Party without cure 4",
"Party without Dervish",
"Mino Add gets lose",
"Sand Orb Explodes",
"Fire Orb Explodes",
"DNC/WHM/AST ping-ponged on wards",
"Forced march in the wrong direction",
"Seeker Fourfold Miscall",
"All Crossover Fourfold Seeker",
"Super Chess Skip in Anyprog",
"Anyprog kills bosses faster than reclear",
"Random DC/Crash",
    "C4 is in your mailbox",
    "Frog Dice",
    "Someone Falls Asleep",
    "One-shot Slimes",
    "Someone doesn't overslot Excellence"
    // For compatibility reasons, the very last item in the list should not have a comma after it.
];
